name: Node.js CI - BDD testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i
      - run: npm test
      - name: Archive the results
        uses: actions/upload-artifact@v1
        with:
          name: cucumber-report
          path: output/cucumber_report.json
